New website with minimal changes required
nodeshift/nodejs-reference-architecture pull request #81
Opened 2021-09-03 20:50 UTC by wtrocki

1. I have put docs as front page for now (better design will follow in separate PR)
2. Minimized changes in the files (although some structure changes were needed)
3. Left Markdown readme functional (for the moment) so github can also be used to view all content

2021-09-03 20:54 UTC, wtrocki commented
@mhdawson reason why website took so long is that introducing it caused multiple conflicts. 
Would it be possible to fastract review on this so it will not happen (This is thrid attempt on website :))

2021-09-03 23:49 UTC, helio-frota requested changes

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> -When publishing modules to npm, it is recommened to enable 2 factor authenticaton.  How to set that up can be found here https://docs.npmjs.com/configuring-two-factor-authentication.  It is also a go
nit recommended
nit authentication

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
>  The use of scoped pacakges is a good practice if you are creating many related packages.
nit packages

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When creating modules that will be published to an internal registry that is not upstream npm, it is a good practice to scope those modules to the name of your organization. It is also important that
nit scoped organization

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When creating modules that will be published to an internal registry that is not upstream npm, it is a good practice to scope those modules to the name of your organization. It is also important that
nit Dependency Confusion

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When creating modules that will be published to an internal registry that is not upstream npm, it is a good practice to scope those modules to the name of your organization. It is also important that
nit accidentally

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +Generally the original sources should not be required to use your published package, but it's your preference whether to publish them or not. Similar to the guidance on tests, the modules that the te
nit publishes

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +It is recommened to use [Semantic Versioning](https://semver.org/) when possible. This will make it easier for a user to determine if a new version of a module will potentianlly break their code.
nit recommended

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +It is recommened to use [Semantic Versioning](https://semver.org/) when possible. This will make it easier for a user to determine if a new version of a module will potentianlly break their code.
nit potentially

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
>  Both of those tools will base the version bump on commit messages that follow the [coventional commit standard](https://www.conventionalcommits.org/en/v1.0.0/)
nit conventional

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When publishing to an internal registry, like Artifactory or Nexus, it is recommended to scope your package. This adds extra protection if this module is accidently published to a public registry and
nit accidentally

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When publishing to an internal registry, like Artifactory or Nexus, it is recommended to scope your package. This adds extra protection if this module is accidently published to a public registry and
nit dependency

2021-09-03 23:49 UTC, helio-frota commented on website/docs/development/npm-publishing.md
> +When publishing to an internal registry, like Artifactory or Nexus, it is recommended to scope your package. This adds extra protection if this module is accidently published to a public registry and
nit recommends

2021-09-04 09:06 UTC, wtrocki commented
@helio-frota thank you for review. I will  apply those suggestions in separate PR. Trying to not make any content changes in this PR. it is only for website publishing

2021-09-04 10:51 UTC, helio-frota commented
@wtrocki  :+1:

2021-09-04 10:52 UTC, helio-frota approved these changes

2021-09-04 11:16 UTC, wtrocki commented
Thank you so much Helio!

2021-09-07 12:21 UTC, BethGriggs approved these changes

2021-09-07 18:44 UTC, lholmquist approved these changes

2021-09-07 20:21 UTC, mhdawson commented
Had short discussion with @wtrocki today. He is going to refactor so that we don't have to move the content to website/docs in the repo. This will avoid breaking existing links and I think will be handled as a copy during the build.

Other than that the changes to the existing docs look like they are only formatting/fixup so look good to me.

2021-09-08 09:36 UTC, wtrocki commented on docs/development/testing.md
> +[babel]: https://babeljs.io
Ok.. So I have run lint but apparently, that doesn't seem to work well with this style of links
Fixing it manually - there were multiple lint issues checked on CI/CD

2021-09-08 09:37 UTC, wtrocki commented on docs/development/apifirst.md
> +---
Removing it.

2021-09-08 10:14 UTC, wtrocki commented
Good review

2021-09-08 15:00 UTC, mhdawson approved these changes
LGTM

2021-09-08 15:00 UTC, merged